import './js/carousel.js';
import './js/mobileMenu.js';
import './js/ModalMVC.js';
import './js/firebase.js';
import './js/firebaseApp.js';
import './scss/base.scss';
import './scss/carousel-style.scss';
import './scss/header.scss';
import './scss/footer.scss';
import Chart from 'chart.js';