import './js/carousel.js';
import './js/mobileMenu.js';
import './js/ModalMVC.js';
import './js/firebase.js';
import './js/gallery.js';
import './js/carMoving.js';
import './js/chart.js';
import './scss/base.scss';
import './scss/carousel-style.scss';
import './scss/header.scss';
import './scss/footer.scss';
import './scss/car.scss';
import Chart from 'chart.js';